services:
  product.api:
    image: productapi
    build:
      context: .
      dockerfile: src/Product/Product.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "80"
      - "5001:443"
